name: Deploy Serverless function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v2
      with:
        token: ${{ secrets.YC_TOKEN }}
        function_id: 'd4eearqeft5kvojp7t0q'
        runtime: 'python311'
        memory: '128'
        entrypoint: 'handler.handler'
        environment: VK_TOKEN=${{ secrets.VK_TOKEN }}
        source: '.'